set(_AMENT_PACKAGE_NAME "polygon_plugins")
set(polygon_plugins_VERSION "0.0.0")
set(polygon_plugins_MAINTAINER "bfmadera <bfmadera@todo.todo>")
set(polygon_plugins_BUILD_DEPENDS "pluginlib" "polygon_base")
set(polygon_plugins_BUILDTOOL_DEPENDS )
set(polygon_plugins_BUILD_EXPORT_DEPENDS "pluginlib" "polygon_base")
set(polygon_plugins_BUILDTOOL_EXPORT_DEPENDS )
set(polygon_plugins_EXEC_DEPENDS "pluginlib" "polygon_base")
set(polygon_plugins_TEST_DEPENDS )
set(polygon_plugins_GROUP_DEPENDS )
set(polygon_plugins_MEMBER_OF_GROUPS )
set(polygon_plugins_DEPRECATED "")
set(polygon_plugins_EXPORT_TAGS)
list(APPEND polygon_plugins_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
list(APPEND polygon_plugins_EXPORT_TAGS "<test_depend>ament_lint_auto</test_depend>")
list(APPEND polygon_plugins_EXPORT_TAGS "<test_depend>ament_lint_common</test_depend>")
